import React from 'react';
import { 
  LayoutDashboard, 
  BarChart3, 
  MessageSquare, 
  Settings, 
  Menu, 
  X, 
  Bell, 
  Search, 
  User, 
  TrendingUp, 
  Users, 
  DollarSign, 
  Activity,
  Send,
  Cpu,
  LogOut,
  Plus,
  Trash2,
  Check,
  CheckCircle2,
  Shield,
  Key,
  Smartphone,
  Mail,
  Save,
  AlertTriangle,
  Globe,
  Lock,
  Eye,
  EyeOff
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Analytics: BarChart3,
  Chat: MessageSquare,
  Settings: Settings,
  Menu: Menu,
  Close: X,
  Bell: Bell,
  Search: Search,
  User: User,
  TrendingUp: TrendingUp,
  Users: Users,
  Dollar: DollarSign,
  Activity: Activity,
  Send: Send,
  Cpu: Cpu,
  LogOut: LogOut,
  Plus: Plus,
  Trash: Trash2,
  Check: Check,
  CheckCircle: CheckCircle2,
  Shield: Shield,
  Key: Key,
  Smartphone: Smartphone,
  Mail: Mail,
  Save: Save,
  AlertTriangle: AlertTriangle,
  Globe: Globe,
  Lock: Lock,
  Eye: Eye,
  EyeOff: EyeOff
};