import React from 'react';
import { 
  LayoutDashboard, 
  BarChart3, 
  MessageSquare, 
  Settings, 
  Menu, 
  X, 
  Bell, 
  Search, 
  User, 
  TrendingUp, 
  Users, 
  DollarSign, 
  Activity,
  Send,
  Cpu,
  LogOut,
  Plus,
  Trash2,
  Check,
  CheckCircle2,
  Shield,
  Key,
  Smartphone,
  Mail,
  Save,
  AlertTriangle,
  Globe,
  Lock,
  Eye,
  EyeOff,
  Download,
  Factory,
  Package,
  Hammer,
  Truck,
  MapPin,
  Calendar,
  Star,
  Filter,
  Phone,
  Map as MapIcon,
  Home,
  Heart,
  Maximize,
  Wifi,
  Music,
  Utensils,
  Car,
  Wine,
  Wind,
  ThumbsUp,
  MessageCircle,
  Clock,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Briefcase
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Analytics: BarChart3,
  Chat: MessageSquare,
  Settings: Settings,
  Menu: Menu,
  Close: X,
  Bell: Bell,
  Search: Search,
  User: User,
  TrendingUp: TrendingUp,
  Users: Users,
  Dollar: DollarSign,
  DollarSign: DollarSign,
  Activity: Activity,
  Send: Send,
  Cpu: Cpu,
  LogOut: LogOut,
  Plus: Plus,
  Trash: Trash2,
  Check: Check,
  CheckCircle: CheckCircle2,
  Shield: Shield,
  Key: Key,
  Smartphone: Smartphone,
  Mail: Mail,
  Save: Save,
  AlertTriangle: AlertTriangle,
  Globe: Globe,
  Lock: Lock,
  Eye: Eye,
  EyeOff: EyeOff,
  Download: Download,
  Factory: Factory,
  Package: Package,
  Hammer: Hammer,
  Truck: Truck,
  MapPin: MapPin,
  Calendar: Calendar,
  Star: Star,
  Filter: Filter,
  Phone: Phone,
  Map: MapIcon,
  Home: Home,
  Heart: Heart,
  Maximize: Maximize,
  Wifi: Wifi,
  Music: Music,
  Utensils: Utensils,
  Car: Car,
  Wine: Wine,
  Wind: Wind,
  ThumbsUp: ThumbsUp,
  MessageCircle: MessageCircle,
  Clock: Clock,
  ChevronDown: ChevronDown,
  ChevronUp: ChevronUp,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Briefcase: Briefcase
};